services:
  llama-cpp-server-gpu:
    build: .
    container_name: llama-cpp-server-gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8585:8585"
    # volumes:
    #   - D:\Vishva\LLamaCPP\models:/models
    command:
      - -m
      - /models/Model-7.6B-Q8_0.gguf
      - --mmproj
      - /models/mmproj-model-f16.gguf
      - --port
      - "8585"
      - --host
      - 0.0.0.0
      - --n-gpu-layers
      - "15000"
      - -n
      - "4096"
      - -t
      - "16"
