services:
  llama-cpp-server:
    build: .
    container_name: llama-cpp-server
    ports:
      - "8000:8000"
    command:
      - -m
      - /models/Model-7.6B-Q4_0.gguf
      # - --no-mmproj-offload
      - --mmproj
      - /models/mmproj-model-f16.gguf
      - --port
      - "8000"
      - --host
      - 0.0.0.0
      - -t
      - "16"
